### ISSUE TITLE
display broken on macOS sierra

### ISSUE THREAD

**Issue by jutkko** [tmux-plugins/tmux-battery#33]

**Comment by andela-cmutembei** [comment]
<img width="216" alt="screen shot 2016-09-21 at 16 58 49" src="https://cloud.githubusercontent.com/assets/10899666/18713944/c4e863e2-801c-11e6-8927-09d5bf1ab7d8.png">

**Comment by jbravar** [comment]
Changing line 10 of `scripts/battery_percentage.sh` to
```
pmset -g batt | awk 'NR==2 { gsub(/;/,""); print $3 }'
```
fixes it. Looks like the version of `pmset` that ships with Sierra reports more than the script expects. This is more of a quick fix, though, since I don't know which other OSes ship with the `pmset` command, and I figure it's still working on those, a more thorough fix would probably require a smarter conditional or something.

**Comment by irliao** [comment]
@jbravar Thank you very much for your quick fix! Just tried it and works! :)

Same quick fix applies for battery remaining, change line 13 of ```scripts/battery_remain.sh``` to
```
local output="$(pmset -g batt | awk 'NR==2 { gsub(/;/,""); print $5 }')"
```

**Comment by jutkko** [comment]
Submitted a pull-request #34
